# Generated by Django 3.1 on 2020-08-12 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=30)),
                ('from_number', models.CharField(max_length=30)),
                ('sms_sid', models.CharField(blank=True, default='', max_length=34)),
                ('account_sid', models.CharField(blank=True, default='', max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 13, 18, 24, 742436, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.FloatField(default=0.0)),
                ('appointment_date', models.DateTimeField(blank=True)),
                ('photos', models.DateTimeField(blank=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
