# Generated by Django 3.1 on 2020-08-13 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0002_auto_20200812_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='booking',
            name='photos',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 12, 34, 45, 642698, tzinfo=utc)),
        ),
    ]
